### ISSUE TITLE
hello blender

### ISSUE THREAD

**Issue by anthonycocilova** [blendermf/XLShredLoader#3]
i cannot get the shred loader to open with f8 it status says okay and my hondunes and replay editor works perfect but f8 will not open for me please help?

**Comment by spundex** [comment]
I got the same issue.

**Comment by s539** [comment]
And I have the same problem. F8 does not show menu.

**Comment by Shoora** [comment]
Me too dont workint f8 after reinstall

**Comment by blendermf** [comment]
This is probably caused by the new versions of Unity Mod Manager. In the code this is already fixed and will be in the next releases. For now, [use this version of Unity Mod Manager](https://github.com/blendermf/XLShredLoader/releases/download/0.0.2/UnityModManagerSkaterXL.zip)(you should be able to upgrade to 0.12.7 from inside it)
